'use client';

import { useState, useEffect } from 'react';

export default function DisclaimerBanner() {
  const [isVisible, setIsVisible] = useState(false);

  useEffect(() => {
    const hasAcknowledged = localStorage.getItem('disclaimer-acknowledged');
    if (!hasAcknowledged) {
      setIsVisible(true);
    }
  }, []);

  const handleAcknowledge = () => {
    localStorage.setItem('disclaimer-acknowledged', 'true');
    setIsVisible(false);
  };

  if (!isVisible) return null;

  return (
    <div className="fixed inset-0 bg-black/80 backdrop-blur-sm z-50 flex items-center justify-center p-4">
      <div className="bg-[var(--card)] border-2 border-[var(--danger)] max-w-2xl w-full p-8 shadow-2xl">
        <div className="text-center mb-6">
          <div className="text-6xl mb-4">⚠️</div>
          <h2 className="text-2xl font-bold text-[var(--danger)] mb-2">
            IMPORTANT LEGAL DISCLAIMER
          </h2>
        </div>

        <div className="space-y-4 text-[var(--text-secondary)] text-sm leading-relaxed max-h-96 overflow-y-auto">
          <div className="bg-[var(--danger)]/10 border border-[var(--danger)]/30 p-4">
            <p className="font-bold text-[var(--danger)] mb-2">🔞 AGE REQUIREMENT</p>
            <p>You must be at least 21 years of age (or the legal gambling age in your jurisdiction) to use this application.</p>
          </div>

          <div>
            <p className="font-bold mb-2">📊 NO GUARANTEES</p>
            <p>
              StakeSmith provides statistical analysis and AI-generated betting strategies for <strong>ENTERTAINMENT AND EDUCATIONAL PURPOSES ONLY</strong>. 
              All predictions, odds analysis, Monte Carlo simulations, and betting recommendations are <strong>NOT GUARANTEES</strong> of future results.
            </p>
          </div>

          <div>
            <p className="font-bold mb-2">💰 FINANCIAL RISK</p>
            <p>
              Sports betting involves substantial financial risk. You may lose money. <strong>NEVER BET MORE THAN YOU CAN AFFORD TO LOSE</strong>. 
              Past performance does not indicate future results. All betting decisions are made at <strong>YOUR OWN RISK</strong>.
            </p>
          </div>

          <div>
            <p className="font-bold mb-2">🎲 GAMBLING ADDICTION WARNING</p>
            <p>
              Gambling can be addictive. If you or someone you know has a gambling problem, call the National Problem Gambling Helpline at 
              <strong> 1-800-522-4700</strong> or visit <a href="https://www.ncpgambling.org" target="_blank" rel="noopener noreferrer" className="text-[var(--accent)] underline">ncpgambling.org</a>.
            </p>
          </div>

          <div>
            <p className="font-bold mb-2">⚖️ LEGAL COMPLIANCE</p>
            <p>
              You are responsible for ensuring that sports betting is legal in your jurisdiction. StakeSmith does not facilitate, process, or accept wagers. 
              We provide analysis tools only. Compliance with all applicable laws is <strong>YOUR RESPONSIBILITY</strong>.
            </p>
          </div>

          <div>
            <p className="font-bold mb-2">🤖 AI-GENERATED CONTENT</p>
            <p>
              Betting strategies and analysis are generated by artificial intelligence and may contain errors, inaccuracies, or outdated information. 
              <strong> DO NOT RELY SOLELY</strong> on AI-generated recommendations. Always conduct your own research and due diligence.
            </p>
          </div>

          <div>
            <p className="font-bold mb-2">📜 NO LIABILITY</p>
            <p>
              StakeSmith and its creators accept <strong>NO LIABILITY</strong> for any losses, damages, or consequences resulting from the use of this application. 
              By using StakeSmith, you acknowledge that all betting decisions are made independently and at your sole discretion.
            </p>
          </div>

          <div className="bg-[var(--warning)]/10 border border-[var(--warning)]/30 p-4">
            <p className="font-bold text-[var(--warning)] mb-2">🎯 RESPONSIBLE GAMBLING</p>
            <p>
              Set betting limits. Never chase losses. Take breaks. Gambling should be entertainment, not a way to make money or solve financial problems.
            </p>
          </div>
        </div>

        <div className="mt-6 space-y-3">
          <label className="flex items-start gap-3 cursor-pointer">
            <input
              type="checkbox"
              id="acknowledge-checkbox"
              className="mt-1"
              onChange={(e) => {
                const btn = document.getElementById('acknowledge-btn') as HTMLButtonElement;
                if (btn) btn.disabled = !e.target.checked;
              }}
            />
            <span className="text-sm text-[var(--text-secondary)]">
              I acknowledge that I have read and understood the above disclaimers. I am of legal gambling age in my jurisdiction. 
              I understand that all betting is done at my own risk with no guarantees of profit.
            </span>
          </label>

          <button
            id="acknowledge-btn"
            onClick={handleAcknowledge}
            disabled
            className="w-full py-3 bg-[var(--danger)] text-white font-bold disabled:opacity-50 disabled:cursor-not-allowed hover:bg-[var(--danger)]/80 transition-colors"
          >
            I Understand and Accept
          </button>
        </div>
      </div>
    </div>
  );
}
